version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.26.0
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin          # default admin user, change as required
      - GF_SECURITY_ADMIN_PASSWORD=admin      # default admin password, change as required
      - GF_USERS_ALLOW_SIGN_UP=false

volumes:
  grafana_data:

  # Define other services here if needed, but it looks like your etcd cluster is already running
